server:
  port: 8080

spring:
  application:
    name: trackwave
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/trackwave}
    username: ${SPRING_DATASOURCE_USERNAME:docker}
    password: ${SPRING_DATASOURCE_PASSWORD:docker}

mybatis:
  type-aliases-package: sbm.domain
  mapper-locations: /mapper/*Mapper.xml

async:
  corePoolSize: 10
  maxPoolSize: 10

storage:
  location: ./storage/