server:
  port: 8080

spring:
  application:
    name: trackwave
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/trackwave}
    username: ${SPRING_DATASOURCE_USERNAME:docker}
    password: ${SPRING_DATASOURCE_PASSWORD:docker}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

async:
  corePoolSize: 10
  maxPoolSize: 10

storage:
  location: ./storage/